# Permalinks
permalink:           pretty

# Setup
title:               Garden
tagline:             Paralelni Polis
url:                 http://paralelnipolis.github.io/garden-blog/
paginate:            1
baseurl:             "https://paralelnipolis.github.io/garden-blog/"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Pavel Kral
  url:               https://www.facebook.com/pavelkral.eu
  email:             pavel@pavelkral.eu

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
